# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

parameters:
    router.class: Clastic\AliasBundle\Routing\Router

services:
    cache.file:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: [%kernel.cache_dir%]